#!/bin/sh

DEV="/dev/dvd"
OPENTIME=10

mode="$1"

case "$mode" in
	toggle)
		eject -T "$DEV"
	;;
	open)
		eject "$DEV"
	;;
	close)
		eject -t "$DEV"
	;;
	startburn)
		eject -t "$DEV"
		eject -i on "$DEV"
	;;
	stopburn)
		eject -i off "$DEV"
		eject "$DEV"
	;;
	getopentime)
		printf "%s\n" "$OPENTIME"
	;;
	getdev)
		printf "$DEV\n"
	;;
	present)
		if [ -n "$(realpath "$DEV" 2> /dev/null)" ]; then
			printf "\"%s\" present\n" "$DEV"
			exit 0
		else
			printf "\"%s\" absent\n" "$DEV"
			exit 1
		fi
	;;
	*)
		printf "Usage: $(basename "$0") {toggle|open|close|startburn|stopburn|getopentime|getdev|present}\n" >&2
	;;
esac

exit 0
